# Dataset Construction Results

### 01. Create face, skin dataset list from full dataset list

In [1]:
import pandas as pd
from pathlib import Path

full_df = pd.read_csv('outputs/full_dataset.csv')

1-1) Face Dataset:

In [5]:
face_df = full_df.copy()

face_df["image_path"] = face_df["image_path"].str.replace(
    "AI_Face_imagesV2", "AI_Face_imagesV2_face", regex=False
)

face_df["Image Path"] = face_df["Image Path"].str.replace(
    "AI_Face_imagesV2", "AI_Face_imagesV2_face", regex=False
)

face_df[["Image Path", "image_path"]].head()

,Image Path,image_path
0,/AI_Face_imagesV2_face/DMs/DCFACe/9152/13.jpg,C:\Users\Young\School\CSC482\Project\AI_Face_i...
1,/AI_Face_imagesV2_face/DMs/DCFACe/3912/24.jpg,C:\Users\Young\School\CSC482\Project\AI_Face_i...
2,/AI_Face_imagesV2_face/GANs/ProGAN images/zip0...,C:\Users\Young\School\CSC482\Project\AI_Face_i...
3,/AI_Face_imagesV2_face/Real/imdb_wiki/imdb/96/...,C:\Users\Young\School\CSC482\Project\AI_Face_i...
4,/AI_Face_imagesV2_face/DMs/StableDiffusion1.5/...,C:\Users\Young\School\CSC482\Project\AI_Face_i...

1-2) Skin Dataset:

In [6]:
skin_df = full_df.copy()

skin_df["image_path"] = skin_df["image_path"].str.replace(
    "AI_Face_imagesV2", "AI_Face_imagesV2_skin", regex=False
)

skin_df["Image Path"] = skin_df["Image Path"].str.replace(
    "AI_Face_imagesV2", "AI_Face_imagesV2_skin", regex=False
)

skin_df[["Image Path", "image_path"]].head()

,Image Path,image_path
0,/AI_Face_imagesV2_skin/DMs/DCFACe/9152/13.jpg,C:\Users\Young\School\CSC482\Project\AI_Face_i...
1,/AI_Face_imagesV2_skin/DMs/DCFACe/3912/24.jpg,C:\Users\Young\School\CSC482\Project\AI_Face_i...
2,/AI_Face_imagesV2_skin/GANs/ProGAN images/zip0...,C:\Users\Young\School\CSC482\Project\AI_Face_i...
3,/AI_Face_imagesV2_skin/Real/imdb_wiki/imdb/96/...,C:\Users\Young\School\CSC482\Project\AI_Face_i...
4,/AI_Face_imagesV2_skin/DMs/StableDiffusion1.5/...,C:\Users\Young\School\CSC482\Project\AI_Face_i...

In [ ]:
# face_df.to_csv("outputs/face_dataset.csv", index=False)
# skin_df.to_csv("outputs/skin_dataset.csv", index=False)

### 02. Processed image path check

In [15]:
face_df["exists"] = face_df["image_path"].apply(lambda p: Path(p).exists())

print(face_df.head())

   Target  Type               Model  \
0       1   DMs              DCFACe
1       1   DMs              DCFACe
2       1  GANs       ProGAN images
3       0  Real           imdb_wiki
4       1   DMs  StableDiffusion1.5

                                          Image Path  Predicted Gender  \
0      /AI_Face_imagesV2_face/DMs/DCFACe/9152/13.jpg                 1
1      /AI_Face_imagesV2_face/DMs/DCFACe/3912/24.jpg                 1
2  /AI_Face_imagesV2_face/GANs/ProGAN images/zip0...                 1
3  /AI_Face_imagesV2_face/Real/imdb_wiki/imdb/96/...                 1
4  /AI_Face_imagesV2_face/DMs/StableDiffusion1.5/...                 0

   Predicted Age  Skin Tone  Skin Tone Group  Intersection    Resolution  \
0              2          5                1             4    (112, 112)
1              4          8                2             5    (112, 112)
2              4          5                1             4  (1024, 1024)
3              3          7                2             5    (244, 244)
4              2          5                1             1    (244, 244)

  dataset                                         image_path  exists
0    test  C:\Users\Young\School\CSC482\Project\AI_Face_i...    True
1    test  C:\Users\Young\School\CSC482\Project\AI_Face_i...    True
2    test  C:\Users\Young\School\CSC482\Project\AI_Face_i...   False
3    test  C:\Users\Young\School\CSC482\Project\AI_Face_i...    True
4    test  C:\Users\Young\School\CSC482\Project\AI_Face_i...   False

In [16]:
face_df["exists"].value_counts(normalize=True)

exists
True     0.74145
False    0.25855
Name: proportion, dtype: float64

In [17]:
face_df_valid = face_df[face_df["exists"] == True]
face_df_valid.to_csv("outputs/face_dataset_valid.csv", index=False)

2-2) Skin Dataset:

In [10]:
skin_df["exists"] = skin_df["image_path"].apply(lambda p: Path(p).exists())

print(skin_df.head())

   Target  Type               Model  \
0       1   DMs              DCFACe
1       1   DMs              DCFACe
2       1  GANs       ProGAN images
3       0  Real           imdb_wiki
4       1   DMs  StableDiffusion1.5

                                          Image Path  Predicted Gender  \
0      /AI_Face_imagesV2_skin/DMs/DCFACe/9152/13.jpg                 1
1      /AI_Face_imagesV2_skin/DMs/DCFACe/3912/24.jpg                 1
2  /AI_Face_imagesV2_skin/GANs/ProGAN images/zip0...                 1
3  /AI_Face_imagesV2_skin/Real/imdb_wiki/imdb/96/...                 1
4  /AI_Face_imagesV2_skin/DMs/StableDiffusion1.5/...                 0

   Predicted Age  Skin Tone  Skin Tone Group  Intersection    Resolution  \
0              2          5                1             4    (112, 112)
1              4          8                2             5    (112, 112)
2              4          5                1             4  (1024, 1024)
3              3          7                2             5    (244, 244)
4              2          5                1             1    (244, 244)

  dataset                                         image_path  exists
0    test  C:\Users\Young\School\CSC482\Project\AI_Face_i...    True
1    test  C:\Users\Young\School\CSC482\Project\AI_Face_i...    True
2    test  C:\Users\Young\School\CSC482\Project\AI_Face_i...   False
3    test  C:\Users\Young\School\CSC482\Project\AI_Face_i...    True
4    test  C:\Users\Young\School\CSC482\Project\AI_Face_i...   False

In [11]:
skin_df["exists"].value_counts(normalize=True)

exists
True     0.74145
False    0.25855
Name: proportion, dtype: float64

In [18]:
skin_df_valid = skin_df[skin_df["exists"] == True]
skin_df_valid.to_csv("outputs/skin_dataset_valid.csv", index=False)